FROM golang:1.19.4 as base
RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
ENV CGO_ENABLED=0
WORKDIR /app
COPY go.* .
RUN go mod download
CMD ["air", "-c", ".air.toml"]
