// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TargetsColumns holds the columns for the "targets" table.
	TargetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"TYPE_HTTP", "TYPE_TCP", "TYPE_PING"}},
		{Name: "interval_seconds", Type: field.TypeUint32},
		{Name: "timeout_seconds", Type: field.TypeUint32},
		{Name: "url", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "hostname", Type: field.TypeString, Nullable: true},
		{Name: "port", Type: field.TypeUint32, Nullable: true},
	}
	// TargetsTable holds the schema information for the "targets" table.
	TargetsTable = &schema.Table{
		Name:       "targets",
		Columns:    TargetsColumns,
		PrimaryKey: []*schema.Column{TargetsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "target_name_type",
				Unique:  true,
				Columns: []*schema.Column{TargetsColumns[1], TargetsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TargetsTable,
	}
)

func init() {
}
